version: '1.0'
services:
    web:
        # depends_on:
        #     - 'base'
        #     - 'backend'
        build:
            context: .
            dockerfile: frontend/Dockerfile
        ports:
            - '3000:3000'
        # environment:
        #     NODE_ENV: staging
    backend:
        # depends_on:
        #     - 'base'
        #     - 'gameserver'
        build:
            context: .
            dockerfile: backend/Dockerfile
        ports:
            - '4000:4000'
        # environment:
        #     NODE_ENV: staging
    gameserver:
        # depends_on:
        #     - 'base'
        build:
            context: .
            dockerfile: gameserver/Dockerfile
        ports:
            - '5000:5000'
            - '6000-7000:6000-7000'
        # environment:
        #     NODE_ENV: staging
